import com.google.gson.annotations.SerializedName

data class NursingRoomDTO(

    @SerializedName("pageNo") val pageNo: Int,
    @SerializedName("countPerPage") val countPerPage: Int,
    @SerializedName("totalCount") val totalCount: Int,
    @SerializedName("firstRegistDate") val firstRegistDate: String,
    @SerializedName("firstRegistUserNo") val firstRegistUserNo: String,
    @SerializedName("firstRegistUserIp") val firstRegistUserIp: String,
    @SerializedName("lastModifyDate") val lastModifyDate: String,
    @SerializedName("lastModifyUserNo") val lastModifyUserNo: String,
    @SerializedName("lastModifyUserIp") val lastModifyUserIp: String,
    @SerializedName("articleNo") val articleNo: String,
    @SerializedName("contentsNo") val contentsNo: String,
    @SerializedName("articleTitle") val articleTitle: String,
    @SerializedName("articleSearchTarget") val articleSearchTarget: String,
    @SerializedName("menuNo") val menuNo: String,
    @SerializedName("menuName") val menuName: String,
    @SerializedName("upperMenuNo") val upperMenuNo: String,
    @SerializedName("upperMenuName") val upperMenuName: String,
    @SerializedName("matchingRate") val matchingRate: Double,
    @SerializedName("roomNo") val roomNo: Int,
    @SerializedName("roomName") val roomName: String,
    @SerializedName("cityName") val cityName: String,
    @SerializedName("zoneName") val zoneName: String,
    @SerializedName("townName") val townName: String,
    @SerializedName("managerName") val managerName: String,
    @SerializedName("managerTelNo") val managerTelNo: String,
    @SerializedName("address") val address: String,
    @SerializedName("location") val location: String,
    @SerializedName("locationName") val locationName: Int,
    @SerializedName("gpsLat") val gpsLat: Double,
    @SerializedName("gpsLong") val gpsLong: Double,
    @SerializedName("cnmx") val cnmx: Double,
    @SerializedName("cnmy") val cnmy: Double,
    @SerializedName("roomTypeCode") val roomTypeCode: Int,
    @SerializedName("beforeWord") val beforeWord: String,
    @SerializedName("afterWord") val afterWord: String,
    @SerializedName("fatherUseYn") val fatherUseYn: Int,
    @SerializedName("startNo") val startNo: Int
)